services:
  - type: web
    name: smart-attendance-system
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        generateValue: true
